### ISSUE TITLE
person.pb validation against person.proto

### ISSUE THREAD

**Issue by Marslanali** [matdoering/python-proto#1]
Hi, 

Thanks for this great start guide and protobuf python example.  How can we validate the generated `person.pb` or `person.protobuf` against the `.proto` file i.e. `person. proto` / `person_info.proto`. 

For instance, after we generate `person.pb` how we are going to make sure that generated `.pb` file is correct? 

```bash
# serialize proto object
import os
out_dir = "proto_dump"
with open(os.path.join(out_dir, "person.pb"), "wb") as f:
    # binary output
    f.write(person.SerializeToString())
with open(os.path.join(out_dir, "person.protobuf"), "w") as f:
    # human-readable output for debugging
    f.write(str(person))
```

I tried with `protoc --decode_raw < person.pb`, however, this does not do the validation just decode the person.pb

Looking forward for any valuable comments.  

Thanks
Arslan

**Comment by mattheiter** [comment]
I guess the naive answer is: if it can't be decoded by `protoc`, then there's something wrong with the protobuf file.
